name: Makefile CI

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Nim
      uses: iffy/install-nim@v4.1.3
      with:
        # 
        version: 1.6.2
      
    - name: build
      run: make
